export const tableData = [
  {
    id: 1,
    name: "John Doe",
    image: "https://placehold.co/100",
    taskStatus: "WORKING",
    email: "john@gmail.com",
    role: "employee",
    isNumeric: false,
  },
  {
    id: 10,
    name: "Emily Davis",
    image: "https://placehold.co/100",
    taskStatus: "WORKING",
    email: "emily@gmail.com",
    role: "employee",
    isNumeric: false,
  },
  {
    id: 11,
    name: "Robert Jones",
    image: "https://placehold.co/100",
    taskStatus: "NOT WORKING",
    email: "robert@gmail.com",
    role: "employee",
    isNumeric: false,
  },
  {
    id: 12,
    name: "Patricia Miller",
    image: "https://placehold.co/100",
    taskStatus: "WORKING",
    email: "patricia@gmail.com",
    role: "employee",
    isNumeric: false,
  },
  {
    id: 13,
    name: "William Wilson",
    image: "https://placehold.co/100",
    taskStatus: "WORKING",
    email: "william@gmail.com",
    role: "employee",
    isNumeric: false,
  },
  {
    id: 14,
    name: "James Brown",
    image: "https://placehold.co/100",
    taskStatus: "WORKING",
    email: "james@gmail.com",
    role: "employee",
    isNumeric: false,
  },
  {
    id: 15,
    name: "Sarah Williams",
    image: "https://placehold.co/100",
    taskStatus: "NOT WORKING",
    email: "sarah@gmail.com",
    role: "employee",
    isNumeric: false,
  },
  {
    id: 16,
    name: "Michael Johnson",
    image: "https://placehold.co/100",
    taskStatus: "NOT WORKING",
    email: "michael@gmail.com",
    role: "employee",
    isNumeric: false,
  },
  {
    id: 17,
    name: "Jane Smith",
    image: "https://placehold.co/100",
    taskStatus: "WORKING",
    email: "jane@gmail.com",
    role: "employee",
    isNumeric: false,
  },
  {
    id: 18,
    name: "John Doe",
    image: "https://placehold.co/100",
    taskStatus: "NOT WORKING",
    email: "john@gmail.com",
    role: "employee",
    isNumeric: false,
  },
];
